import Head from 'next/head';
import styles from '../styles/Home.module.css';
import NavBar from '../src/components/NavBar';
import HeroHome from '../src/components/HeroHome';
import Description from '../src/components/Description';
import Events from '../src/components/Events';
import Partnership from '../src/components/Partnership';
import Testimonial from '../src/components/Testimonial';
import Footer from '../src/components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Empower Her Community</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <NavBar />
      <HeroHome />
      <Description />
      <Events />
      <Partnership />
      <Testimonial />
      <Footer />
    </div>
  )
}
