import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../src/components/NavBar";
import HeroHome from "../src/components/HeroHome";
import Description from "../src/components/Description";
import Events from "../src/components/Events";
import Partnership from "../src/components/Partnership";
import Testimonial from "../src/components/Testimonial";
import Footer from "../src/components/Footer";
import PopUp from "../src/components/Popup";

export default function Home() {
  const [popup, setPopup] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      setPopup(true);
    }, 12000);
  }, []);

  const closePopup = () => {
    setPopup(false);
  };
  return (
    <div className="overflow-hidden">
      <Head>
        <title>Empower Her Community Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        <meta
          property="og:url"
          content={window.location.pathname + window.location.search}
        />
        <meta property="og:image" content="/logo.png" />
      </Head>
      {popup && <PopUp closePopup={closePopup}></PopUp>}
      <NavBar />
      <main className="main overflow-hidden">
        <HeroHome />
        <Description />
        <Events />
        <Partnership />
        <Testimonial />
      </main>
      <Footer />
    </div>
  );
}
